import {Roboto_Mono} from "next/font/google"
import "./globals.css";

const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${roboto_mono.variable} ${roboto_mono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
